src/controllers/ErrorController.php
<?php

namespace bedezign\yii2\audit\controllers;

use bedezign\yii2\audit\components\web\Controller;
use bedezign\yii2\audit\models\AuditError;
use bedezign\yii2\audit\models\AuditErrorSearch;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * ErrorController
 * @package bedezign\yii2\audit\controllers
 */
class ErrorController extends Controller
{
    /**
     * Lists all AuditError models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuditErrorSearch;
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel'  => $searchModel,
        ]);
    }

    /**
     * Displays a single AuditError model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = AuditError::findOne($id);
        if (!$model) {
            throw new NotFoundHttpException('The requested error does not exist.');
        }
        return $this->render('view', [
            'model' => $model,
        ]);
    }
}

src/views/entry/panels/soap/detail.php
<?php
/* @var $panel bedezign\yii2\audit\panels\SoapPanel */

use yii\bootstrap\Tabs;
use yii\helpers\Html;
use bedezign\yii2\audit\components\Helper;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;

$preformatted = ['class' => 'well', 'style' => 'overflow: auto; white-space: pre'];
$formatter = \Yii::$app->formatter;

//echo "<pre>" . ;
$tabs = [];

if (isset($request['result_object'])) {
    $tabs[] = [
        'label' => \Yii::t('audit', 'Result - Object'),
        'content' => Html::tag('div', $formatter->asText(VarDumper::dumpAsString(ArrayHelper::toArray($request['result_object']))), $preformatted)
    ];

    unset($request['result_object']);
}

if (isset($request['result'])) {
    $xml = Helper::formatAsXML($request['result']);
    if ($xml)
        $tabs[] = [
            'label' => \Yii::t('audit', 'Result - XML'),
            'content' => Html::tag('div', $xml, $preformatted)
        ];

    $tabs[] = [
        'label' => \Yii::t('audit', 'Result'),
        'content' => Html::tag('div', $formatter->asText($request['result']), $preformatted)
    ];

    unset($request['result']);
}

$tabs[] = [ 'label' => \Yii::t('audit', 'Info'), 'content' => $this->render('info_table', ['request' => $request]), 'active' => true ];

echo Html::tag('h2', \Yii::t('audit', 'Request #{id}', ['id' => $index])), Tabs::widget(['items' => array_reverse($tabs)]);

src/views/entry/panels/soap/index.php
<?php
/* @var $panel yii\debug\panels\LogPanel */

use yii\helpers\Html;
use yii\grid\GridView;

echo Html::tag('h1', $panel->name);

foreach ($dataProvider->allModels as $index => $request)
    echo $this->render('detail', ['panel' => $panel, 'request' => $request, 'index' => $index + 1]);

src/views/entry/panels/soap/info_table.php
<?php

use yii\helpers\Html;
use yii\helpers\VarDumper;
use yii\helpers\Url;



$formatter = \Yii::$app->formatter;

if (isset($request['error']) && isset($request['error'][1])) {
    $error = \bedezign\yii2\audit\models\AuditError::findOne($request['error'][1]);
    $request['error'] = Html::a('[' . $request['error'][0] . '] ' . $error->message, ['error/view', 'id' => $error->id]);
}

?>
<div class="table-responsive">
    <table class="table table-condensed table-bordered table-striped table-hover request-table" style="table-layout: fixed;">
        <thead>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($request as $name => $value): ?>
            <tr>
                <th><?= Html::encode(\yii\helpers\Inflector::humanize($name)) ?></th>
                <td>
<?php
    if (is_array($value) || is_object($value))
        $value = \yii\helpers\ArrayHelper::toArray($value);
    elseif ($name == 'duration')
        $value = number_format($value, 2) . 's';
    echo $name == 'error' ? $value : $formatter->asText(is_scalar($value) ? $value : VarDumper::dumpAsString($value));
?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>